# Generated by Django 5.1.2 on 2024-10-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpost',
            name='comments',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
