# Generated by Django 5.1.2 on 2024-10-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_remove_addpost_comments_alter_addpost_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpost',
            name='images',
            field=models.ImageField(default='uploads/default.jpg', upload_to='uploads/'),
        ),
    ]
